### ISSUE TITLE
Does not work with vertical panels

### ISSUE THREAD

**Issue by attila123** [cinnamon-applets/system-monitor-applet#6]
Nice applet, but it does not work if I move my cinnamon panel to vertical position. This was a long awaited feature of cinnamon which was recently released (e.g. with Linux Mint 18.1).

**Comment by cbojar** [comment]
Sorry, but this project is no longer maintained. I recommend you use https://cinnamon-spices.linuxmint.com/applets/view/198 for similar functionality.
